# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Daniel Rozek
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
favicon: /favicon.ico
include:
  - _includes/main.html
github_username: Crispruby
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Daniel Rozek"
  avatar : "/assets/images/Photo.jpg"
  bio    : "Computer Information Systems graduate degree. Interest and experienced in Programming, Databases and SQL, Fusion 360, Unity, and 3D Modeling. Seeking opportunities in software development, database development, game development and 3D modeling."
  links:
  - label: "LinkedIn"
    icon: "fab fa-fw fa-linkedin"
    url: "https://www.linkedin.com/in/danielrozek/"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/crispruby"
  - label: "Credly Badges"
    icon: "fas fa-fw fa-link"
    url: "https://www.credly.com/users/daniel-rozek"
  - label: "Digital Shop of Goodies" 
    icon: "fas fa-fw fa-link" 
    url: "https://www.etsy.com/ca/shop/DigitalShopOfGoodies" 
  - label: "Unity Video Games"
    icon: "fas fa-fw fa-link"
    url: "https://play.unity.com/en/user/e55dbe35-9b86-4769-9484-485ac138cf1c"
  - label: "Itch.io Video Games" 
    icon: "fas fa-fw fa-link" 
    url: "https://captain-garneto.itch.io/"
  - label: "Athlete Profile"
    icon: "assets/images/Icon.png"
    url: "https://crispruby.github.io/daniel_rozek_sports/about/"
  - label: "Geocache"
    icon: "assets/images/Geo.png"
    url: "https://www.geocaching.com/p/default.aspx"
  - label: "Strava"
    icon: "assets/images/strava24.jpg" #"fas fa-fw fa-link" 
    url: "https://www.strava.com/athletes/danielrozek"
    #- label: "YouTube" icon: "fab fa-fw fa-youtube" url: "https://"
    #- label: "Instagram" icon: "fab fa-fw fa-instagram" "url: "http://instagram.com/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danielrozek/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/crispruby"
    #- label: "Instagram" icon: "fab fa-fw fa-instagram" url: "https://instagram.com/"
    
assets:
  stylesheets:
    - /assets/css/main.css
    - /assets/css/custom.css
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
